<h1>About</h1>
<p>倉儲:<a href="https://github.com/40823218/CAD2020">https://github.com/40823218/CAD2020</a></p>
<p><img alt="" height="451" src="/images/42791037_1967703943250389_1264928487840415744_n.jpg" width="400"/></p>
<p></p>
<h1>每周進度</h1>
<p></p>
<h2>W1 SolidWorks零件繪圖練習1(43~50)</h2>
<p><a href="/downloads/pdf1(43~50).rar">下載檔案</a></p>
<p>雲端硬碟:<a href="https://drive.google.com/file/d/1R-k9Tc4n0GJcVOwbVKYUTtr6We0VoCz7/view">https://drive.google.com/file/d/1R-k9Tc4n0GJcVOwbVKYUTtr6We0VoCz7/view</a></p>
<p><iframe height="1000" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vT8kqEWxCnP-IYOQSHiSVZDxP5PALsOsTr7R98W91FnibQDIoEeojJZmNdp7ubl-7pDP3pl2PTJvujQ/pubhtml?gid=0&amp;single=true&amp;widget=true&amp;headers=false" width="600"></iframe></p>
<p><img alt="" height="217" src="/images/gaitubao_SLDWORKS_BMnWdwmmAN.png" width="400"/></p>
<p><img alt="" height="217" src="/images/gaitubao_SLDWORKS_EHVihIFnLb.png" width="400"/></p>
<p><img alt="" height="217" src="/images/gaitubao_SLDWORKS_GO6ORjgVlY.png" width="400"/></p>
<p><img alt="" height="217" src="/images/gaitubao_SLDWORKS_J5YB2zY0qg.png" width="400"/></p>
<p><img alt="" height="217" src="/images/gaitubao_SLDWORKS_pJCaMpklzP.png" width="400"/></p>
<p><img alt="" height="217" src="/images/gaitubao_SLDWORKS_vDeMXrYqS5.png" width="400"/></p>
<p><img alt="" height="217" src="/images/gaitubao_SLDWORKS_9KzqnWaxt3.png" width="400"/></p>
<p><img alt="" height="217" src="/images/gaitubao_SLDWORKS_16OS8WndQO.png" width="400"/></p>
<h2>W2</h2>
<p>PDF:<a href="http://mde.tw/cad2020/downloads/nx_python_examples.pdf">http://mde.tw/cad2020/downloads/nx_python_examples.pdf</a></p>
<h2>W4</h2>
<p>PDF1零件43</p>
<p><iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/Yvg6Tx6r5rI" width="560"></iframe></p>
<h2>W7 ANSI C</h2>
<p><a href="/downloads/ansi c 試用.rar">下載</a></p>
<p><img alt="" height="208" src="/images/test.png" width="277"/></p>
<h2>W8</h2>
<p>NX</p>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false"># nx_open_part.py
# 導入 NXOpen
import NXOpen
import NXOpen.UF
import NXOpen.Gateway
    
def main():
    # 取得目前開啟的工作階段
    theSession = NXOpen.Session.GetSession()
    theUfSession = NXOpen.UF.UFSession.GetUFSession()
       
    # 建立 ListingWindow
    listWin= theSession.ListingWindow
    # 開啟零件檔案
    basePart1 = theSession.Parts.OpenBaseDisplay("y:/tmp/block.prt")
    workPart = theSession.Parts.Work
    unit1 = workPart.UnitCollection.FindObject("MilliMeter")
    # height
    p7 = workPart.Expressions.FindObject("p7")
    # width
    p8 = workPart.Expressions.FindObject("p8")
    # length
    p9 = workPart.Expressions.FindObject("p9")
    workPart.Expressions.EditWithUnits(p7, unit1, "30")
    workPart.Expressions.EditWithUnits(p8, unit1, "60")
    workPart.Expressions.EditWithUnits(p9, unit1, "90")
    theSession.UpdateManager.DoUpdate(0)
    #saveStatus1 = workPart.SaveAs("y:/tmp/block_new.prt")
    #saveStatus1.Dispose()
    # initialize list to hold bodies
    theBodyTags = []
    
    for x in workPart.Bodies:
        if x.IsSolidBody:
            theBodyTags.append(x.Tag)
       
    # 準備輸出 ASCII 格式 STL 零件檔案
    sTLCreator1 = theSession.DexManager.CreateStlCreator()
    sTLCreator1.AutoNormalGen = True
    sTLCreator1.ChordalTol = 0.08
    sTLCreator1.AdjacencyTol = 0.08
    sTLCreator1.OutputFile = "y:\\tmp\\block_ascii.stl"
    # Binary STL: NXOpen.STLCreatorOutputTypeEnum.Binary
    sTLCreator1.OutputType = NXOpen.STLCreatorOutputTypeEnum.Text
    # 已知 body1 命名
    body1 = workPart.Bodies.FindObject("EXTRUDE(2)")
    added1 = sTLCreator1.ExportSelectionBlock.Add(body1)
    nXObject1 = sTLCreator1.Commit()
    sTLCreator1.Destroy()
   
    # 開啟所建立的 ListingWindow
    listWin.Open()
    listWin.WriteLine("number of solid bodies: " + str(len(theBodyTags)))
    
    (massProps, Stats) = theUfSession.Modeling.AskMassProps3d(theBodyTags, len(theBodyTags), 1, 4, .03, 1, [0.99,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0])
    listWin.WriteLine("units: kg, mm")
    listWin.WriteLine("surface area: " + str(massProps[0]))
    listWin.WriteLine("volume: " + str(massProps[1]*1E9))
    # 在 ListingWindow 中寫入字串
    listWin.WriteLine("Hello, NXOpen")
    listWin.Close()
      
    # 將零件檔案 fit 之後, export 出 png 檔案
    theUI = NXOpen.UI.GetUI()
    imageExportBuilder1 = theUI.CreateImageExportBuilder()
  
    custombackgroundcolor1 = [None] * 3
    custombackgroundcolor1[0] = 1.0
    custombackgroundcolor1[1] = 1.0
    custombackgroundcolor1[2] = 1.0
  
    imageExportBuilder1.SetCustomBackgroundColor(custombackgroundcolor1)
    imageExportBuilder1.FileFormat = NXOpen.Gateway.ImageExportBuilder.FileFormats.Png
    imageExportBuilder1.FileName = "y:\\tmp\\block.png"
  
    imageExportBuilder1.BackgroundOption = NXOpen.Gateway.ImageExportBuilder.BackgroundOptions.Original
  
    imageExportBuilder1.EnhanceEdges = False
    imageExportBuilder1.RegionMode = False
    # fit view 後 commit export png
    workPart.ModelingViews.WorkView.Fit()
    nXObject6 = imageExportBuilder1.Commit()
  
    imageExportBuilder1.Destroy()
       
if __name__ == "__main__":
    main()</pre>
<h1>小組作業</h1>
<h2>影片</h2>
<p><strong>因輪軸尺寸與外框相同，因而產生干涉。</strong><iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/_SN9tZHclfo" width="560"></iframe><strong>修改後</strong><iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/Gzb5EJkI4X4" width="560"></iframe><strong>將輪軸由5修改為4</strong></p>
<p><img alt="" height="185" src="/images/修改前.png" width="250"/><img alt="" height="191" src="/images/修改後.png" width="250"/></p>
<p><strong>輪軸旁導桿尺寸修改後，可完成一次行程</strong></p>
<p><iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/tvgRd39CdSI" width="560"></iframe></p>